server:
  port: 8080

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    #表示是否将自己注册进EurekaService,默认为true
    register-with-eureka: true
    #是否从EurekaService抓取已有得注册信息，默认为true。单节点无所谓，集群必须设置为true,才能配合ribbon使用负载均衡
    fetchRegistry: true
    #入住地址
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka/ 单机版
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ #集群版
  instance:
    instance-id: order8080  #配置eureka图形界面显示的名称，规范化处理(主机名称：服务名称的修改)
    prefer-ip-address: true #访问信息是有IP显示的，方便以后排查问题
